config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get 'about' => 'static_pages#about'
  get 'publications' => 'publications#index'
  post 'publications' => 'publications#create'
  get 'publications/new' => 'publications#new'
  get 'publications/:id' => 'publications#show', as: :publication
  patch 'publications/:id' => 'publications#update'
  get 'publications/:id/edit' => 'publications#edit', as: :edit_publication
  delete 'publications/:id' => 'publications#destroy'
  
  get 'users/:user_id/publications' => 'publications#index', as: :user_publications

  get 'sessions/new'
  get 'users' => 'users#index'
  get 'users/new' => 'users#new'
  post 'users' => 'users#create'

  get '/login' => 'users#login'
  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get 'users/index'

end

app/models/publication.rb
class Publication < ActiveRecord::Base
	belongs_to :user
	belongs_to :topic
	mount_uploader :file, FileUploader
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :publications
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :publications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :null_session
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController

  def index
    if params[:user_id]
    	@user = User.find(params[:user_id])
      @publications = @user.publications
    else
      @publications = Publication.all
    end

  end

  def new
    @user = User.find(session[:user_id])
    @publication = @user.publications.new
    @topics = Topic.all
  end

  def show
    @publication = Publication.find(params[:id])
  end

  def edit
    @publication = Publication.find(params[:id])
    @topics = Topic.all
  end

  def destroy
   @publication = Publication.find(params[:id])
   @publication.destroy
   redirect_to publications_path 
  end

  def update
    @publication = Publication.find(params[:id])
    if @publication.update_attributes(publication_params)
      redirect_to publication_path
    else
      render :edit
    end
  end

  def create
    # @publication = Publication.new
    @user = User.find(session[:user_id])
    @publication = @user.publications.new(publication_params)

  	if @publication.save
      # render text: 'publication saved'
  		redirect_to publications_path
  	else
  		render :new
  	end
  end

  private

  def publication_params
      params.require(:publication).permit(:title, :publication_date, :synopsis, :topic_id, :file)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @users = User.all
    @publications = Publication.all
  end

  def create
  	user = User.find_by(user_name: params[:user_name])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		# render text: 'user is logged in'
  		redirect_to publications_path
  	else 
  		render 'users/login'
  	end
  end

  def destroy
  	session.delete(:user_id)
  	redirect_to '/'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def landing
		@publications=Publication.last(3)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
    @publications = Publication.all
  end

  def new
    @user = User.new
  end

  def create
  	@user = User.new({
  		user_name: params[:user_name],
  		password: params[:password],
  		password_confirmation: params[:password_confirmation]
  		})
  	if @user.save
      session[:user_id] = @user.id
  		redirect_to '/'
  	else
  		render :new
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntiApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class ="container">
	<% if current_user %>
		<ul class="nav nav-pills">
			<li role="presentation"><%= link_to 'Home', root_path%></li>
			<li role="presentation"><%= link_to 'All Publications', publications_path%></li>
			<li role="presentation"><%= link_to 'Your Publications', user_publications_path(current_user)%></li>
			<li role="presentation"><%= link_to 'Add a Publication', publications_new_path %></li>
			<li><%= link_to 'Log Out', logout_path, method: :delete %></li>
		</ul>
	<% end %>



	<%= yield %>
</div>

</body>
</html>

app/views/publications/_form.html.erb
<%= form_for(@publication, {html: {class: "form-group"}}) do |f| %>
	<div class = "form-group">
		<%= f.label(:title) %>
		<%= f.text_field :title, :class => 'form-control' %>
	</div>

	<div <class = "form-group">
		<%= f.label(:publication_date) %>
		<%= f.date_field :publication_date, :class => 'form-control' %>
	</div>

		<div <class = "form-group" >
		<%= f.label(:topic_id) %>
		<%= f.collection_select(:topic_id, @topics.all, :id, :name) %>
	</div>

	<div < class = "form-group" >
		<%= f.label(:synopsis) %>
		<%= f.text_area :synopsis, :class => 'form-control' %>
	</div>

	<div < class = "form-group" >
		<%= f.label(:file) %>
		<%= f.file_field :file %>
	</div> 


	<%= f.submit({class: "btn btn-success"}) %>
<% end %>

app/views/publications/edit.html.erb
<h2> Edit Item </h2>
<%= render 'form' %>
<%= link_to 'Back', @publication %>

app/views/publications/index.html.erb
<% if current_user %>
	<%= "Welcome #{current_user.user_name}"%>
<% else %>
	<%= link_to 'Sign In', login_path, :class => 'btn btn-success' %>
<% end %>

<h1>Publications</h1>

<ul>
	<% @publications.each do |publication| %>
		<li>
		<%= link_to(publication.title, publication_path(publication))%>
		, <%= publication.publication_date %></li>
	<% end %>
</ul>









 

app/views/publications/new.html.erb
<h2> Add Publications </h2>
<%= render 'form' %>

app/views/publications/show.html.erb
<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Date Published</th>
            <th>Synopsis</th>
            <th>Topic</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= @publication.title %></td>
            <td><%= @publication.user.user_name %></td>
            <td><%= @publication.publication_date %></td>
            <td><%= @publication.synopsis %></td>
            <td><%= @publication.topic.name %></td>
        </tr>
 </table>
<br>

<%= link_to 'Download Paper', @publication.file_url %>
<br>
<%#= image_tag publication.file_url.to_s %>

<% if current_user and @publication.user.id == current_user.id %>
<%= link_to "Edit", {:controller => :publications, :action => 'edit'},
 :method => :get %><br>

 <%= link_to "Delete", publication_path, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>
<br>

 <%= link_to 'Back', publications_path %>

app/views/static_pages/about.html.erb
<br>
<h2>Inti<h2>
 <%= image_tag "sol.png" %>
<ul>
	<h4>Inti is a community-driven collection of research publications where  you can access and submit research publications for free!</h4>

	<h4>If you are the author of a research paper, simply make an account and upload your publications for others to enjoy.</h4>

	<h4>Share your knowledge!</h4>
</ul>

app/views/static_pages/landing.html.erb
<div class="jumbotron">
  <h1>Welcome to Inti</h1>
  <%= image_tag "sol.png" %>
  <p>Inti is a community-driven collection of research publications where  you can access and submit research publications for free!</p>
  <p><a class="btn btn-primary btn-lg" href="/about" role="button">Learn more</a></p>
  <%= link_to 'Log In', login_path, :class => 'btn btn-info' %>
    <%= link_to 'Sign Up', users_new_path, :class => 'btn btn-warning' %>
</div>

<h2>Latest Publications</h2>
<div class="row">
    <% @publications.each do |publication| %>
    <%# publication.user.user_name %> 
    <%#= publication.publication_date %>
 

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "paper.png" %>
      <div class="caption">
        <h3><%=publication.title%></h3>
        <p><%= publication.synopsis %></p>
        <p><%= link_to("go to", publication_path(publication), { class:"btn btn-primary", role:"button"})%>
         <%= link_to(publication.user.user_name, user_publications_path(publication.user), { class:"btn btn-default", role:"button"})%></p>
      </div>
    </div>
  </div>
    <% end %>

app/views/users/index.html.erb
<% if current_user%>
	<h3>Your publications</h3><br>

	<% current_user.publications.each do |publication| %>
		<li><%= publication.title %></li>
	<% end %>
<% end %>

app/views/users/login.html.erb
  <% if !current_user %>

  <!-- form to log in -->
  <div class = "form-group">
    <form action="/login" method="post">
      <label>User Name</label>
      <input class="form-control" name="user_name" type="text" placeholder="username">

      <label>Password</label>
      <input class="form-control" name="password" type="password" placeholder="password">
      
      <button type"button" class = "btn btn-success">Log In</button>
    </form>
  </div>

  <%#= link_to 'Sign Up', users_new_path, :class => 'btn btn-warning' %>
<!--   <form action="/users/new" method="get"> 
 <button>Sign Up</button> 
</form>  -->

  <%# else %>
  <!-- <form action="/logout" method="post">
    <input name="_method" value="DELETE" type="hidden">
  <button>Logout</button> -->
  <!-- </form> -->
  <% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<!-- form to sign up and make account -->

<form action="/users" method="post">
  <label>User Name</label>
  <input name="user_name" type="text" placeholder="user_name">

  <label>Password</label>
  <input name="password" type="password" placeholder="password">

  <label>Password Confirmation</label>
  <input name="password_confirmation" type="password" placeholder="password confirmation">

  <button>Sign Up</button>
</form>